import type { Metadata } from "next";
import { Fraunces, Bricolage_Grotesque, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ToastContainer } from "@/components/ui/toast";
import { Navbar } from "@/components/layout/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { FileContextProvider } from "@/context/FileContext";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import Footer from "@/components/layout/footer";

// Display font - Editorial, distintiva para headings
const fraunces = Fraunces({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

// Body font - Grotesca moderna, única y legible
const bricolage = Bricolage_Grotesque({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

// Monospace - Técnica y precisa
const jetbrains = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fraunces.variable} ${bricolage.variable} ${jetbrains.variable} antialiased min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ErrorBoundary level="app">
            <FileContextProvider>
              <Navbar />
              {children}
              <Footer />
              <Toaster />
              <ToastContainer position="bottom-right" maxVisible={5} />
            </FileContextProvider>
          </ErrorBoundary>
        </ThemeProvider>
      </body>
    </html>
  );
}
